#!/bin/bash

# Restores the database from backups generated by mongodump.

# .env should be a file with the MONGODB_USERNAME and MONGODB_PASSWORD in the same directory as this file
# defined as bash variables (a standard .env file should do the trick)
source .env
CLUSTER_URL="qbreader2.z35tynb"
URI="mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${CLUSTER_URL}.mongodb.net/?retryWrites=true&w=majority"
mongorestore -d qbreader -c tossups --uri=$URI tossups.bson
mongorestore -d qbreader -c bonuses --uri=$URI bonuses.bson
mongorestore -d qbreader -c packets --uri=$URI packets.bson
mongorestore -d qbreader -c sets --uri=$URI sets.bson
