(() => {
  const D = window.BOWL_DATA; const G = window.BOWL_GENERATOR; const oldGenerate = G.generate;
  const pick = a => a[Math.floor(Math.random() * a.length)];
  const vocab = new Map(D.vocab.map(v => [v.rank, v]));
  const lex = new Map(); for (const v of D.vocab) { const l = v.lemma.toLowerCase(); if (/^[a-záéíóúüñ]+$/.test(l) && !lex.has(l))lex.set(l, v); }
  const forms = { años: 'año', meses: 'mes', días: 'día', semanas: 'semana', estudiando: 'estudiar', trabajando: 'trabajar', viviendo: 'vivir', aprendiendo: 'aprender', llevo: 'llevar', llevas: 'llevar', lleva: 'llevar', llevamos: 'llevar', llevan: 'llevar', levanto: 'levantar', levantas: 'levantar', levantamos: 'levantar', acuesto: 'acostar', acuesta: 'acostar', acostamos: 'acostar', gustan: 'gustar', gusta: 'gustar', encanta: 'encantar', encantan: 'encantar', dará: 'dar', entregará: 'entregar', devolverá: 'devolver', perdió: 'perder', cuesta: 'costar', dura: 'durar', empieza: 'empezar', cierra: 'cerrar', quiero: 'querer', quiere: 'querer', trabaja: 'trabajar', tengo: 'tener', tienes: 'tener', tenemos: 'tener', tuviera: 'tener', supiera: 'saber', pudiera: 'poder', viviera: 'vivir', sé: 'saber', entiendo: 'entender', ha: 'haber', he: 'haber', has: 'haber', hemos: 'haber', han: 'haber', está: 'estar', estaba: 'estar', estábamos: 'estar', estaban: 'estar', es: 'ser', minutos: 'minuto', horas: 'hora', euros: 'euro' };
  const match = s => [...new Map((s.toLowerCase().match(/[a-záéíóúüñ]+/g) || []).map(w => lex.get(forms[w] || w)).filter(Boolean).map(v => [v.rank, v])).values()];
  const obj = (rank, group = 'objects') => pick(G.groups[group].filter(o => o.v.rank <= rank));
  const families = {
    'Object pronouns': rank => { const p = pick([['Te lo', 'it to you'], ['Se lo', 'it to him/her/you/them'], ['Nos lo', 'it to us'], ['Me lo', 'it to me']]); const a = pick([['dará', 'will give'], ['entregará', 'will hand'], ['devolverá', 'will return']]); return [`${p[0]} ${a[0]} mañana.`, `He/she will ${a[1].replace('will ', '')} ${p[1]} tomorrow.`, 'Spanish does not specify whether the giver is he, she, or formal you. For se, several recipients are possible.']; },
    'Accidental events': rank => { const o = obj(rank); return [`Se me perdió ${o.es}.`, `I lost ${o.en}.`, 'Also accept “' + o.en + ' got lost on me.” The construction presents the loss as unintentional.']; },
    Duration: rank => { const p = pick([['Llevo', 'I have'], ['Llevas', 'You have'], ['Lleva', 'He/she has'], ['Llevamos', 'We have'], ['Llevan', 'They have']]); const t = pick([['dos años', 'two years'], ['tres meses', 'three months'], ['una semana', 'a week'], ['cinco días', 'five days']]); const a = pick([['estudiando español', 'studying Spanish'], ['trabajando aquí', 'working here'], ['viviendo en Madrid', 'living in Madrid'], ['aprendiendo francés', 'learning French']]); return [`${p[0]} ${t[0]} ${a[0]}.`, `${p[1]} been ${a[1]} for ${t[1]}.`, 'Preserve the duration and the fact that the activity continues into the present.']; },
    Comparisons: rank => { const x = pick([['Este libro', 'This book', 'aquel', 'that one'], ['Esta mesa', 'This table', 'aquella', 'that one'], ['Este abrigo', 'This coat', 'aquel', 'that one'], ['Esta silla', 'This chair', 'aquella', 'that one']]); const a = pick([['caro', 'expensive'], ['grande', 'large'], ['pesado', 'heavy']]); const f = x[0].startsWith('Esta') && a[0].endsWith('o') ? a[0].slice(0, -1) + 'a' : a[0]; const more = Math.random() < 0.5; return [`${x[0]} es ${more ? 'más' : 'menos'} ${f} que ${x[2]}.`, `${x[1]} is ${more ? 'more' : 'less'} ${a[1]} than ${x[3]}.`, 'Equivalent comparative wording is fine: e.g., “larger” for “more large.”']; },
    Negation: rank => { const a = pick([['Todavía no ha llegado nadie.', 'Nobody has arrived yet.'], ['No quiero nada de la tienda.', 'I do not want anything from the store.'], ['Nunca hemos estado en ese museo.', 'We have never been to that museum.'], ['Nadie sabe dónde está la llave.', 'Nobody knows where the key is.'], ['Ella tampoco quiere salir hoy.', 'She does not want to go out today either.'], ['No tengo ningún libro de historia.', 'I do not have any history books.'], ['Ya no trabaja en esa escuela.', 'He/she no longer works at that school.']]); return [...a, 'Watch the scope of the negative and words such as yet, either, never, and no longer.']; },
    'Past contrast': rank => { const s = pick([['Yo', 'I', 'estaba', 'was'], ['Ella', 'She', 'estaba', 'was'], ['Nosotros', 'We', 'estábamos', 'were'], ['Ellos', 'They', 'estaban', 'were']]); const a = pick([['durmiendo', 'sleeping'], ['estudiando', 'studying'], ['comiendo', 'eating'], ['leyendo', 'reading']]); const event = pick([['sonó el teléfono', 'the phone rang'], ['llegó el profesor', 'the teacher arrived'], ['empezó a llover', 'it started to rain']]); return [`${s[0]} ${s[2]} ${a[0]} cuando ${event[0]}.`, `${s[1]} ${s[3]} ${a[1]} when ${event[1]}.`, 'Distinguish the ongoing background action from the event that happened.']; },
    'Relative clauses': rank => { const o = obj(rank, 'objects'); const a = pick([['vi', 'saw'], ['perdí', 'lost'], ['encontré', 'found'], ['necesito', 'need']]); return [`${o.es[0].toUpperCase() + o.es.slice(1)} que ${a[0]} está aquí.`, `${o.en[0].toUpperCase() + o.en.slice(1)} that I ${a[1]} is here.`, '“That” can be omitted in natural English.']; },
    Hypotheticals: rank => { const a = pick([['tuviera tiempo', 'had time', 'iría contigo', 'would go with you'], ['tuviera dinero', 'had money', 'compraría una bicicleta', 'would buy a bicycle'], ['supiera la respuesta', 'knew the answer', 'te la diría', 'would tell you the answer'], ['viviera más cerca', 'lived closer', 'vendría más a menudo', 'would come more often'], ['pudiera viajar', 'could travel', 'visitaría España', 'would visit Spain']]); return [`Si yo ${a[0]}, ${a[2]}.`, `If I ${a[1]}, I ${a[3]}.`, 'This is a hypothetical situation, not a statement that the condition is true.']; },
    'Perfect tenses': rank => { const p = pick([['Yo', 'I', 'he'], ['Tú', 'You', 'has'], ['Ella', 'She', 'ha'], ['Nosotros', 'We', 'hemos'], ['Ellos', 'They', 'han']]); const o = obj(rank, 'objects'); const a = pick([['encontrado', 'found'], ['perdido', 'lost'], ['traído', 'brought']]); return [`${p[0]} ya ${p[2]} ${a[0]} ${o.es}.`, `${p[1]} ${p[1] === 'She' ? 'has' : 'have'} already ${a[1]} ${o.en}.`, 'Natural simple-past English may also fit, especially in American English. Preserve “already.”']; },
    Location: rank => { const o = obj(rank); const l = pick([['debajo de la mesa', 'under the table'], ['encima de la silla', 'on top of the chair'], ['al lado de la puerta', 'next to the door'], ['dentro de la caja', 'inside the box'], ['detrás del sofá', 'behind the sofa']]); return [`${o.es[0].toUpperCase() + o.es.slice(1)} está ${l[0]}.`, `${o.en[0].toUpperCase() + o.en.slice(1)} is ${l[1]}.`, 'Preserve the spatial relationship.']; },
    Reflexives: rank => { const a = pick([['Me levanto', 'I get up'], ['Te levantas', 'You get up'], ['Nos levantamos', 'We get up'], ['Me acuesto', 'I go to bed'], ['Se acuesta', 'He/she goes to bed'], ['Nos acostamos', 'We go to bed']]); const late = a[0].includes('acuest') || a[0].includes('acosta'); const t = pick(late ? [['a las diez', 'at ten'], ['a las once', 'at eleven'], ['a medianoche', 'at midnight']] : [['a las seis', 'at six'], ['a las siete', 'at seven'], ['al amanecer', 'at dawn']]); return [`${a[0]} ${t[0]}.`, `${a[1]} ${t[1]}.`, 'In context, a simple present or habitual reading is appropriate.']; },
    'Likes & feelings': rank => { const p = pick([['Me', 'I'], ['Te', 'You'], ['Nos', 'We']]); const a = pick([['gustan las manzanas', 'like apples'], ['gusta el queso', 'like cheese'], ['encanta leer', 'love reading'], ['gusta esta canción', 'like this song'], ['gustan esos zapatos', 'like those shoes'], ['encantan los libros de historia', 'love history books']]); return [`${p[0]} ${a[0]}.`, `${p[1]} ${a[1]}.`, 'The Spanish grammatical subject is the thing liked; natural English reverses this structure.']; },
    Obligation: rank => { const p = pick([['Tengo que', 'I have to'], ['Tienes que', 'You have to'], ['Tenemos que', 'We have to']]); const a = pick([['devolver los libros', 'return the books'], ['terminar la tarea', 'finish the homework'], ['limpiar la cocina', 'clean the kitchen'], ['estudiar para el examen', 'study for the exam']]); const t = pick([['hoy', 'today'], ['antes del viernes', 'before Friday'], ['esta noche', 'tonight']]); return [`${p[0]} ${a[0]} ${t[0]}.`, `${p[1]} ${a[1]} ${t[1]}.`, '“Must” is also acceptable when it preserves the obligation.']; },
    'Time & quantity': rank => { const n = pick([['dos', 'two'], ['tres', 'three'], ['cinco', 'five'], ['diez', 'ten'], ['veinte', 'twenty']]); const x = pick([['El billete cuesta', 'The ticket costs', 'euros', 'euros'], ['El viaje dura', 'The trip lasts', 'horas', 'hours'], ['La clase empieza en', 'The class starts in', 'minutos', 'minutes'], ['La tienda cierra en', 'The store closes in', 'minutos', 'minutes']]); return [`${x[0]} ${n[0]} ${x[2]}.`, `${x[1]} ${n[1]} ${x[3]}.`, 'Preserve the number and unit.']; }
  };
  const seen = new Set();
  function generate (rank = 2000, focus = 'mixed') {
    let fallback = null;
    for (let i = 0; i < 120; i++) {
      const f = focus === 'mixed' ? pick([...Object.keys(families), 'present', 'preterite', 'imperfect', 'future', 'conditional', 'commands', 'subjunctive', 'expressions']) : focus;
      let q;
      if (families[f]) { const a = families[f](rank); if (!a) continue; const ts = match(a[0]); const content = ts.filter(v => v.tags.some(t => ['nm', 'nf', 'adj', 'v', 'adv', 'nc', 'nm/f'].includes(t))); if (!content.some(v => v.rank <= rank)) continue; q = { id: 'g2:' + a[0], spanish: a[0], english: a[1], note: a[2], grammar: f, skills: [f], targets: content.filter(v => v.rank <= rank), ranks: content.filter(v => v.rank <= rank).map(v => v.rank), source: 'Generated · ' + f, origin: 'generated' }; } else { q = oldGenerate(rank, f); if (!q) continue; q.skills = [q.grammar]; q.ranks = q.targets.map(v => v.rank); q.origin = 'generated'; }
      q.words = q.spanish.split(/\s+/).length; fallback = q;
      if (!seen.has(q.spanish) || i === 119) { seen.add(q.spanish); return q; }
    }
    return fallback;
  }
  G.generate = generate; G.families = Object.keys(families); G.match = match; G.vocabByRank = vocab;
})();
